[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
name = "function_2"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proxy-wasm = { path = "../proxy-wasm" }
