global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - '127.0.0.1:9090'

  - job_name: 'layotto'
    scheme: http
    static_configs:
      - targets:
        - 'docker.for.mac.localhost:34903'