name: Layotto Env Pipeline 🌊

# Deadlink Validation will auto run at 0:00 am everyday.
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - '**/*.md'
    types: [opened, edited, reopened, synchronize]
    branches:
      - main

jobs:
  check:
    name: "DeadLink Validation"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install markdown-link-check
        run: sudo npm install -g markdown-link-check@3

      - name: Install and start docsify server
        run: |
             sudo npm i docsify-cli -g
             nohup docsify serve docs -p 3000 &

      - name: Check dead links in all the .md files
        run: make deadlink  
